name: Update Shared Assets (content/common)

on:
  repository_dispatch:
    types: [common-update]

jobs:
  Update-Common-Submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CSK_PAT }}
          submodules: recursive
          fetch-depth: 0

      - name: Update common submodule pointer
        uses: ianhub/github-actions/update-submodule@main
        with:
          path: skeleton
          branch: content/common
