name: Update Shared Assets (content/common)

on:
  repository_dispatch:
    types: [common-update]

jobs:
  update_common_submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CSK_PAT }}
          submodules: recursive

      - name: Update common submodule pointer
        run: |
          git submodule update --remote content/common
          git add content/common
          if ! git diff --quiet; then
            git commit -m "Update common submodule pointer due to common changes"
            git push
          else
            echo "Common submodule already up to date"
          fi
