name: Update Core Files (skeleton)

on:
  repository_dispatch:
    types: [core-update]

jobs:
  update_core_submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CSK_PAT }}
          submodules: recursive

      - name: Update core submodule pointer
        run: |
          git submodule update --remote skeleton
          git add skeleton
          if ! git diff --quiet; then
            git commit -m "Update core submodule pointer due to core changes"
            git push
          else
            echo "Core submodule already up to date"
          fi
